version: '2'

services:
  db:
    build: db
    env_file: env.env
    ports:
     - 5432:5432
  api:
    build: api
    env_file: env.env
    command: python /code/runserver.py
    ports:
      - 5000:5000
    volumes:
      - ./api:/code
    depends_on:
      - db
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./web:/usr/share/nginx/html
    depends_on:
      - api
