version: '2'

services:
  db:
    build: .
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    ports:
     - 5432:5432
  api:
    build: api
    command: python /code/app.py
    ports:
      - 5000:5000
    depends_on:
      - db
