version: '2'

services:
  db:
    image: postgres
    env_file: env.env
    ports:
     - 5432:5432
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/audio_data:/audio_data
  api:
    build: api
    env_file: env.env
    command: python /code/runserver.py
    ports:
      - 5000:5000
    volumes:
      - ./api:/code
    depends_on:
      - db
    entrypoint: ./wait-for-it.sh db:5432 --
  web:
    build: web
    ports:
      - 8000:80
    volumes:
      - ./web:/usr/share/nginx/html
    depends_on:
      - api
